#ifndef SPLITRULE_H
#define SPLITRULE_H

#include <vector>
#include "Rule.h"
#include "Clause.h"

namespace cnf
{
    class SplitRule : public Rule
    {
        private:
            const Clause clause;

        public:
            /**
             * Constructor for SplitRule.
             * 
             * @param clause The clause to be split.
             */
            SplitRule(const Clause& clause);

            /**
             * Destructor for SplitRule.
             */
            ~SplitRule();

            /**
             * Apply the split rule.
             * 
             * @return A vector of new clauses generated by the split rule.
             */
            std::vector<Clause> apply() const override;

            /**
             * Get the clause in the split rule.
             * 
             * @return The clause.
             */
            const Clause& getClause() const;

            /**
             * Print the split rule to the standard output.
             */
            void print() const override;

            /**
             * Get the clause at the specified index.
             * 
             * @param index The index of the clause (0 for the first clause).
             * @return The clause at the specified index.
             */
            const Clause &operator[](const std::size_t index) const override;
    };
}

#endif